# POST https://fs-part3.onrender.com/api/persons
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#   "name": "New Person",
#   "number": "83928292 232"
# }


DELETE http://localhost:3001/api/persons/delete/650ada65bb738118346ed3f5
# GET http://localhost:3001/api/persons/650ab741b4d8d61cdb09162d
