# POST https://fs-part3.onrender.com/api/persons
# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#   "name": "New Person",
#   "number": "83928292 232"
# }


# DELETE http://localhost:3001/api/persons/delete/650ada65bb738118346ed3f5
GET http://localhost:3001/api/persons/650a7f19c22efeadf48ec965
